[Bug-Fix] When If use ThisObject, init class fail.
Error msg:
    File "/home/milk/py35/lib/python3.5/site-packages/viewflow/nodes/ifgate.py",
    line 68, in _resolve
    self._condition = getattr(self.flow_class.instance, self._condition.name)
    AttributeError: 'NoneType' object has no attribute 'instance'

Root Cause:
    When FlowClass init the metaclass with flow_class = None,
    when If node resove get condition will fail.

Fix:
    Add condition in property condition to excute the func then
    return True or False